version: '3.8'
services:
  db:
    image: postgres:16
    container_name: chat-postgres
    environment:
      - POSTGRES_DB=chatdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-network

  chat-server:
    build:
      context: ./chat-app-server
    ports:
      - "9090:9090"
    networks:
      - chat-network
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/chatdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update


  chat-client:
    build:
      context: ./chat_app_client
    networks:
      - chat-network
    stdin_open: true
    tty: true

networks:
  chat-network:
    driver: bridge

volumes:
  postgres_data:
