spring.application.name=chat-app-server

spring.datasource.url=jdbc:postgresql://ep-delicate-leaf-a1iw9m2c-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_IcDUa8Oy9PrV

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

